linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - maligned
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  # Run with --fast=false for more extensive checks
  fast: true
issues:
  max-same-issues: 0
  max-per-linter: 0
  # List of regexps of issue texts to exclude, empty list by default.
  exclude:
    - Using the variable on range scope `(tc)|(rt)|(tt)|(test)|(testcase)|(testCase)` in function literal
    - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
run:
  timeout: 10m
  tests: false
  skip-files:
    - "zz_generated.*\\.go$"
    - ".*_mock\\.go"
