linters:
  enable:
    - golint
    - govet
    - gofmt
    - structcheck
    - varcheck
    - interfacer
    - unconvert
    - ineffassign
    - goconst
    - gocyclo
    - maligned
    - misspell
    - nakedret
    - prealloc
    - gosec
    - deadcode
  disable-all: true
  # Run with --fast=false for more extensive checks
  fast: true
issue:
  max-same-issues: 0
  max-per-linter: 0
