- op: add
  path: "/spec/template/spec/containers/-"
  value:
    name: kube-rbac-proxy
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
    args:
    - "--secure-listen-address=0.0.0.0:8443"
    - "--upstream=http://127.0.0.1:8080/"
    - "--logtostderr=true"
    - "--v=10"
    ports:
    - containerPort: 8443
      name: https
