apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: awsmachineproviderconfigs.awsproviderconfig.k8s.io
spec:
  group: awsproviderconfig.k8s.io
  names:
    kind: AWSMachineProviderConfig
    plural: awsmachineproviderconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalSecurityGroups:
              items:
                properties:
                  arn:
                    type: string
                  filters:
                    items:
                      properties:
                        name:
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      required:
                      - name
                      - values
                      type: object
                    type: array
                  id:
                    type: string
                type: object
              type: array
            additionalTags:
              type: object
            ami:
              properties:
                arn:
                  type: string
                filters:
                  items:
                    properties:
                      name:
                        type: string
                      values:
                        items:
                          type: string
                        type: array
                    required:
                    - name
                    - values
                    type: object
                  type: array
                id:
                  type: string
              type: object
            iamInstanceProfile:
              type: string
            instanceType:
              type: string
            keyName:
              type: string
            publicIP:
              type: boolean
            subnet:
              properties:
                arn:
                  type: string
                filters:
                  items:
                    properties:
                      name:
                        type: string
                      values:
                        items:
                          type: string
                        type: array
                    required:
                    - name
                    - values
                    type: object
                  type: array
                id:
                  type: string
              type: object
          required:
          - ami
          - instanceType
          - keyName
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastProbeTime:
                    format: date-time
                    type: string
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                - lastProbeTime
                - lastTransitionTime
                - reason
                - message
                type: object
              type: array
            instanceID:
              type: string
            instanceState:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
