apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: awsmachineproviderspecs.awsprovider.k8s.io
spec:
  group: awsprovider.k8s.io
  names:
    kind: AWSMachineProviderSpec
    plural: awsmachineproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        additionalSecurityGroups:
          items:
            properties:
              arn:
                type: string
              filters:
                items:
                  properties:
                    name:
                      type: string
                    values:
                      items:
                        type: string
                      type: array
                  required:
                  - name
                  - values
                  type: object
                type: array
              id:
                type: string
            type: object
          type: array
        additionalTags:
          type: object
        ami:
          properties:
            arn:
              type: string
            filters:
              items:
                properties:
                  name:
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - name
                - values
                type: object
              type: array
            id:
              type: string
          type: object
        apiVersion:
          type: string
        iamInstanceProfile:
          type: string
        instanceType:
          type: string
        keyName:
          type: string
        kind:
          type: string
        metadata:
          type: object
        publicIP:
          type: boolean
        subnet:
          properties:
            arn:
              type: string
            filters:
              items:
                properties:
                  name:
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - name
                - values
                type: object
              type: array
            id:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
