resources:
  - provider-non-stamped-base.yaml
  - cluster_api.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: aws-provider-controller-manager
    path: stateful-set-credentials-patch.yaml
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: aws-provider-controller-manager
    path: manager-version-patch.yaml
