nameprefix: capa-webhook-
namespace: capi-webhook-system

bases:
- ../certmanager
- ../manager

resources:
- service.yaml
- service_account.yaml
- webhook_configuration.yaml

commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-aws"

configurations:
- kustomizeconfig.yaml

patchesStrategicMerge:
- webhookcainjection_patch.yaml

patchesJson6902:
# Repeat this definition for each new CRD under crd/bases
- target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
    namespace: system
  path: patch_manager_webhook.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
    namespace: system
  path: patch_service_account.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: leader-election-rolebinding
    namespace: system
  path: patch_rolebinding.yaml

vars:
- name: CERTIFICATE_NAMESPACE
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1alpha2
    name: serving-cert
  fieldref:
    fieldpath: metadata.namespace
- name: CERTIFICATE_NAME
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1alpha2
    name: serving-cert
- name: SERVICE_NAMESPACE
  objref:
    kind: Service
    version: v1
    name: controller
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: controller

