// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	clusterapiproviderawsapiv1alpha3 "sigs.k8s.io/cluster-api-provider-aws/api/v1alpha3"
	clusterapiproviderawsapiv1alpha4 "sigs.k8s.io/cluster-api-provider-aws/api/v1alpha4"
	v1alpha4 "sigs.k8s.io/cluster-api-provider-aws/exp/api/v1alpha4"
	apiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
	apiv1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AWSFargateProfile)(nil), (*v1alpha4.AWSFargateProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSFargateProfile_To_v1alpha4_AWSFargateProfile(a.(*AWSFargateProfile), b.(*v1alpha4.AWSFargateProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSFargateProfile)(nil), (*AWSFargateProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSFargateProfile_To_v1alpha3_AWSFargateProfile(a.(*v1alpha4.AWSFargateProfile), b.(*AWSFargateProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSFargateProfileList)(nil), (*v1alpha4.AWSFargateProfileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSFargateProfileList_To_v1alpha4_AWSFargateProfileList(a.(*AWSFargateProfileList), b.(*v1alpha4.AWSFargateProfileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSFargateProfileList)(nil), (*AWSFargateProfileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSFargateProfileList_To_v1alpha3_AWSFargateProfileList(a.(*v1alpha4.AWSFargateProfileList), b.(*AWSFargateProfileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSLaunchTemplate)(nil), (*v1alpha4.AWSLaunchTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSLaunchTemplate_To_v1alpha4_AWSLaunchTemplate(a.(*AWSLaunchTemplate), b.(*v1alpha4.AWSLaunchTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSLaunchTemplate)(nil), (*AWSLaunchTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSLaunchTemplate_To_v1alpha3_AWSLaunchTemplate(a.(*v1alpha4.AWSLaunchTemplate), b.(*AWSLaunchTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSMachinePool)(nil), (*v1alpha4.AWSMachinePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSMachinePool_To_v1alpha4_AWSMachinePool(a.(*AWSMachinePool), b.(*v1alpha4.AWSMachinePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSMachinePool)(nil), (*AWSMachinePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSMachinePool_To_v1alpha3_AWSMachinePool(a.(*v1alpha4.AWSMachinePool), b.(*AWSMachinePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSMachinePoolInstanceStatus)(nil), (*v1alpha4.AWSMachinePoolInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSMachinePoolInstanceStatus_To_v1alpha4_AWSMachinePoolInstanceStatus(a.(*AWSMachinePoolInstanceStatus), b.(*v1alpha4.AWSMachinePoolInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSMachinePoolInstanceStatus)(nil), (*AWSMachinePoolInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSMachinePoolInstanceStatus_To_v1alpha3_AWSMachinePoolInstanceStatus(a.(*v1alpha4.AWSMachinePoolInstanceStatus), b.(*AWSMachinePoolInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSMachinePoolList)(nil), (*v1alpha4.AWSMachinePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSMachinePoolList_To_v1alpha4_AWSMachinePoolList(a.(*AWSMachinePoolList), b.(*v1alpha4.AWSMachinePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSMachinePoolList)(nil), (*AWSMachinePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSMachinePoolList_To_v1alpha3_AWSMachinePoolList(a.(*v1alpha4.AWSMachinePoolList), b.(*AWSMachinePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSMachinePoolSpec)(nil), (*v1alpha4.AWSMachinePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSMachinePoolSpec_To_v1alpha4_AWSMachinePoolSpec(a.(*AWSMachinePoolSpec), b.(*v1alpha4.AWSMachinePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSMachinePoolSpec)(nil), (*AWSMachinePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSMachinePoolSpec_To_v1alpha3_AWSMachinePoolSpec(a.(*v1alpha4.AWSMachinePoolSpec), b.(*AWSMachinePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSMachinePoolStatus)(nil), (*v1alpha4.AWSMachinePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSMachinePoolStatus_To_v1alpha4_AWSMachinePoolStatus(a.(*AWSMachinePoolStatus), b.(*v1alpha4.AWSMachinePoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSMachinePoolStatus)(nil), (*AWSMachinePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSMachinePoolStatus_To_v1alpha3_AWSMachinePoolStatus(a.(*v1alpha4.AWSMachinePoolStatus), b.(*AWSMachinePoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSManagedCluster)(nil), (*v1alpha4.AWSManagedCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSManagedCluster_To_v1alpha4_AWSManagedCluster(a.(*AWSManagedCluster), b.(*v1alpha4.AWSManagedCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSManagedCluster)(nil), (*AWSManagedCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSManagedCluster_To_v1alpha3_AWSManagedCluster(a.(*v1alpha4.AWSManagedCluster), b.(*AWSManagedCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSManagedClusterList)(nil), (*v1alpha4.AWSManagedClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSManagedClusterList_To_v1alpha4_AWSManagedClusterList(a.(*AWSManagedClusterList), b.(*v1alpha4.AWSManagedClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSManagedClusterList)(nil), (*AWSManagedClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSManagedClusterList_To_v1alpha3_AWSManagedClusterList(a.(*v1alpha4.AWSManagedClusterList), b.(*AWSManagedClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSManagedClusterSpec)(nil), (*v1alpha4.AWSManagedClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSManagedClusterSpec_To_v1alpha4_AWSManagedClusterSpec(a.(*AWSManagedClusterSpec), b.(*v1alpha4.AWSManagedClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSManagedClusterSpec)(nil), (*AWSManagedClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSManagedClusterSpec_To_v1alpha3_AWSManagedClusterSpec(a.(*v1alpha4.AWSManagedClusterSpec), b.(*AWSManagedClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSManagedClusterStatus)(nil), (*v1alpha4.AWSManagedClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSManagedClusterStatus_To_v1alpha4_AWSManagedClusterStatus(a.(*AWSManagedClusterStatus), b.(*v1alpha4.AWSManagedClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSManagedClusterStatus)(nil), (*AWSManagedClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSManagedClusterStatus_To_v1alpha3_AWSManagedClusterStatus(a.(*v1alpha4.AWSManagedClusterStatus), b.(*AWSManagedClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSManagedMachinePool)(nil), (*v1alpha4.AWSManagedMachinePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSManagedMachinePool_To_v1alpha4_AWSManagedMachinePool(a.(*AWSManagedMachinePool), b.(*v1alpha4.AWSManagedMachinePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSManagedMachinePool)(nil), (*AWSManagedMachinePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSManagedMachinePool_To_v1alpha3_AWSManagedMachinePool(a.(*v1alpha4.AWSManagedMachinePool), b.(*AWSManagedMachinePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSManagedMachinePoolList)(nil), (*v1alpha4.AWSManagedMachinePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSManagedMachinePoolList_To_v1alpha4_AWSManagedMachinePoolList(a.(*AWSManagedMachinePoolList), b.(*v1alpha4.AWSManagedMachinePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSManagedMachinePoolList)(nil), (*AWSManagedMachinePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSManagedMachinePoolList_To_v1alpha3_AWSManagedMachinePoolList(a.(*v1alpha4.AWSManagedMachinePoolList), b.(*AWSManagedMachinePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSManagedMachinePoolSpec)(nil), (*v1alpha4.AWSManagedMachinePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSManagedMachinePoolSpec_To_v1alpha4_AWSManagedMachinePoolSpec(a.(*AWSManagedMachinePoolSpec), b.(*v1alpha4.AWSManagedMachinePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AWSManagedMachinePoolStatus)(nil), (*v1alpha4.AWSManagedMachinePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSManagedMachinePoolStatus_To_v1alpha4_AWSManagedMachinePoolStatus(a.(*AWSManagedMachinePoolStatus), b.(*v1alpha4.AWSManagedMachinePoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AWSManagedMachinePoolStatus)(nil), (*AWSManagedMachinePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSManagedMachinePoolStatus_To_v1alpha3_AWSManagedMachinePoolStatus(a.(*v1alpha4.AWSManagedMachinePoolStatus), b.(*AWSManagedMachinePoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AutoScalingGroup)(nil), (*v1alpha4.AutoScalingGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AutoScalingGroup_To_v1alpha4_AutoScalingGroup(a.(*AutoScalingGroup), b.(*v1alpha4.AutoScalingGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AutoScalingGroup)(nil), (*AutoScalingGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AutoScalingGroup_To_v1alpha3_AutoScalingGroup(a.(*v1alpha4.AutoScalingGroup), b.(*AutoScalingGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BlockDeviceMapping)(nil), (*v1alpha4.BlockDeviceMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BlockDeviceMapping_To_v1alpha4_BlockDeviceMapping(a.(*BlockDeviceMapping), b.(*v1alpha4.BlockDeviceMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.BlockDeviceMapping)(nil), (*BlockDeviceMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_BlockDeviceMapping_To_v1alpha3_BlockDeviceMapping(a.(*v1alpha4.BlockDeviceMapping), b.(*BlockDeviceMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EBS)(nil), (*v1alpha4.EBS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_EBS_To_v1alpha4_EBS(a.(*EBS), b.(*v1alpha4.EBS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.EBS)(nil), (*EBS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_EBS_To_v1alpha3_EBS(a.(*v1alpha4.EBS), b.(*EBS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FargateProfileSpec)(nil), (*v1alpha4.FargateProfileSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_FargateProfileSpec_To_v1alpha4_FargateProfileSpec(a.(*FargateProfileSpec), b.(*v1alpha4.FargateProfileSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.FargateProfileSpec)(nil), (*FargateProfileSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_FargateProfileSpec_To_v1alpha3_FargateProfileSpec(a.(*v1alpha4.FargateProfileSpec), b.(*FargateProfileSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FargateProfileStatus)(nil), (*v1alpha4.FargateProfileStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_FargateProfileStatus_To_v1alpha4_FargateProfileStatus(a.(*FargateProfileStatus), b.(*v1alpha4.FargateProfileStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.FargateProfileStatus)(nil), (*FargateProfileStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_FargateProfileStatus_To_v1alpha3_FargateProfileStatus(a.(*v1alpha4.FargateProfileStatus), b.(*FargateProfileStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FargateSelector)(nil), (*v1alpha4.FargateSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_FargateSelector_To_v1alpha4_FargateSelector(a.(*FargateSelector), b.(*v1alpha4.FargateSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.FargateSelector)(nil), (*FargateSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_FargateSelector_To_v1alpha3_FargateSelector(a.(*v1alpha4.FargateSelector), b.(*FargateSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstancesDistribution)(nil), (*v1alpha4.InstancesDistribution)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_InstancesDistribution_To_v1alpha4_InstancesDistribution(a.(*InstancesDistribution), b.(*v1alpha4.InstancesDistribution), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.InstancesDistribution)(nil), (*InstancesDistribution)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_InstancesDistribution_To_v1alpha3_InstancesDistribution(a.(*v1alpha4.InstancesDistribution), b.(*InstancesDistribution), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedMachinePoolScaling)(nil), (*v1alpha4.ManagedMachinePoolScaling)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_ManagedMachinePoolScaling_To_v1alpha4_ManagedMachinePoolScaling(a.(*ManagedMachinePoolScaling), b.(*v1alpha4.ManagedMachinePoolScaling), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.ManagedMachinePoolScaling)(nil), (*ManagedMachinePoolScaling)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ManagedMachinePoolScaling_To_v1alpha3_ManagedMachinePoolScaling(a.(*v1alpha4.ManagedMachinePoolScaling), b.(*ManagedMachinePoolScaling), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedRemoteAccess)(nil), (*v1alpha4.ManagedRemoteAccess)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_ManagedRemoteAccess_To_v1alpha4_ManagedRemoteAccess(a.(*ManagedRemoteAccess), b.(*v1alpha4.ManagedRemoteAccess), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.ManagedRemoteAccess)(nil), (*ManagedRemoteAccess)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ManagedRemoteAccess_To_v1alpha3_ManagedRemoteAccess(a.(*v1alpha4.ManagedRemoteAccess), b.(*ManagedRemoteAccess), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MixedInstancesPolicy)(nil), (*v1alpha4.MixedInstancesPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MixedInstancesPolicy_To_v1alpha4_MixedInstancesPolicy(a.(*MixedInstancesPolicy), b.(*v1alpha4.MixedInstancesPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MixedInstancesPolicy)(nil), (*MixedInstancesPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MixedInstancesPolicy_To_v1alpha3_MixedInstancesPolicy(a.(*v1alpha4.MixedInstancesPolicy), b.(*MixedInstancesPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Overrides)(nil), (*v1alpha4.Overrides)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Overrides_To_v1alpha4_Overrides(a.(*Overrides), b.(*v1alpha4.Overrides), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Overrides)(nil), (*Overrides)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Overrides_To_v1alpha3_Overrides(a.(*v1alpha4.Overrides), b.(*Overrides), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RefreshPreferences)(nil), (*v1alpha4.RefreshPreferences)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_RefreshPreferences_To_v1alpha4_RefreshPreferences(a.(*RefreshPreferences), b.(*v1alpha4.RefreshPreferences), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.RefreshPreferences)(nil), (*RefreshPreferences)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_RefreshPreferences_To_v1alpha3_RefreshPreferences(a.(*v1alpha4.RefreshPreferences), b.(*RefreshPreferences), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1alpha3.APIEndpoint)(nil), (*apiv1alpha4.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(a.(*apiv1alpha3.APIEndpoint), b.(*apiv1alpha4.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*clusterapiproviderawsapiv1alpha3.AWSResourceReference)(nil), (*clusterapiproviderawsapiv1alpha4.AWSResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AWSResourceReference_To_v1alpha4_AWSResourceReference(a.(*clusterapiproviderawsapiv1alpha3.AWSResourceReference), b.(*clusterapiproviderawsapiv1alpha4.AWSResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1alpha4.APIEndpoint)(nil), (*apiv1alpha3.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(a.(*apiv1alpha4.APIEndpoint), b.(*apiv1alpha3.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.AWSManagedMachinePoolSpec)(nil), (*AWSManagedMachinePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSManagedMachinePoolSpec_To_v1alpha3_AWSManagedMachinePoolSpec(a.(*v1alpha4.AWSManagedMachinePoolSpec), b.(*AWSManagedMachinePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*clusterapiproviderawsapiv1alpha4.AWSResourceReference)(nil), (*clusterapiproviderawsapiv1alpha3.AWSResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AWSResourceReference_To_v1alpha3_AWSResourceReference(a.(*clusterapiproviderawsapiv1alpha4.AWSResourceReference), b.(*clusterapiproviderawsapiv1alpha3.AWSResourceReference), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_AWSFargateProfile_To_v1alpha4_AWSFargateProfile(in *AWSFargateProfile, out *v1alpha4.AWSFargateProfile, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_FargateProfileSpec_To_v1alpha4_FargateProfileSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_FargateProfileStatus_To_v1alpha4_FargateProfileStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AWSFargateProfile_To_v1alpha4_AWSFargateProfile is an autogenerated conversion function.
func Convert_v1alpha3_AWSFargateProfile_To_v1alpha4_AWSFargateProfile(in *AWSFargateProfile, out *v1alpha4.AWSFargateProfile, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSFargateProfile_To_v1alpha4_AWSFargateProfile(in, out, s)
}

func autoConvert_v1alpha4_AWSFargateProfile_To_v1alpha3_AWSFargateProfile(in *v1alpha4.AWSFargateProfile, out *AWSFargateProfile, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_FargateProfileSpec_To_v1alpha3_FargateProfileSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_FargateProfileStatus_To_v1alpha3_FargateProfileStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AWSFargateProfile_To_v1alpha3_AWSFargateProfile is an autogenerated conversion function.
func Convert_v1alpha4_AWSFargateProfile_To_v1alpha3_AWSFargateProfile(in *v1alpha4.AWSFargateProfile, out *AWSFargateProfile, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSFargateProfile_To_v1alpha3_AWSFargateProfile(in, out, s)
}

func autoConvert_v1alpha3_AWSFargateProfileList_To_v1alpha4_AWSFargateProfileList(in *AWSFargateProfileList, out *v1alpha4.AWSFargateProfileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.AWSFargateProfile)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_AWSFargateProfileList_To_v1alpha4_AWSFargateProfileList is an autogenerated conversion function.
func Convert_v1alpha3_AWSFargateProfileList_To_v1alpha4_AWSFargateProfileList(in *AWSFargateProfileList, out *v1alpha4.AWSFargateProfileList, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSFargateProfileList_To_v1alpha4_AWSFargateProfileList(in, out, s)
}

func autoConvert_v1alpha4_AWSFargateProfileList_To_v1alpha3_AWSFargateProfileList(in *v1alpha4.AWSFargateProfileList, out *AWSFargateProfileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AWSFargateProfile)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_AWSFargateProfileList_To_v1alpha3_AWSFargateProfileList is an autogenerated conversion function.
func Convert_v1alpha4_AWSFargateProfileList_To_v1alpha3_AWSFargateProfileList(in *v1alpha4.AWSFargateProfileList, out *AWSFargateProfileList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSFargateProfileList_To_v1alpha3_AWSFargateProfileList(in, out, s)
}

func autoConvert_v1alpha3_AWSLaunchTemplate_To_v1alpha4_AWSLaunchTemplate(in *AWSLaunchTemplate, out *v1alpha4.AWSLaunchTemplate, s conversion.Scope) error {
	out.Name = in.Name
	out.IamInstanceProfile = in.IamInstanceProfile
	if err := Convert_v1alpha3_AWSResourceReference_To_v1alpha4_AWSResourceReference(&in.AMI, &out.AMI, s); err != nil {
		return err
	}
	out.ImageLookupFormat = in.ImageLookupFormat
	out.ImageLookupOrg = in.ImageLookupOrg
	out.ImageLookupBaseOS = in.ImageLookupBaseOS
	out.InstanceType = in.InstanceType
	out.RootVolume = (*clusterapiproviderawsapiv1alpha4.Volume)(unsafe.Pointer(in.RootVolume))
	out.SSHKeyName = (*string)(unsafe.Pointer(in.SSHKeyName))
	out.VersionNumber = (*int64)(unsafe.Pointer(in.VersionNumber))
	if in.AdditionalSecurityGroups != nil {
		in, out := &in.AdditionalSecurityGroups, &out.AdditionalSecurityGroups
		*out = make([]clusterapiproviderawsapiv1alpha4.AWSResourceReference, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_AWSResourceReference_To_v1alpha4_AWSResourceReference(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.AdditionalSecurityGroups = nil
	}
	return nil
}

// Convert_v1alpha3_AWSLaunchTemplate_To_v1alpha4_AWSLaunchTemplate is an autogenerated conversion function.
func Convert_v1alpha3_AWSLaunchTemplate_To_v1alpha4_AWSLaunchTemplate(in *AWSLaunchTemplate, out *v1alpha4.AWSLaunchTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSLaunchTemplate_To_v1alpha4_AWSLaunchTemplate(in, out, s)
}

func autoConvert_v1alpha4_AWSLaunchTemplate_To_v1alpha3_AWSLaunchTemplate(in *v1alpha4.AWSLaunchTemplate, out *AWSLaunchTemplate, s conversion.Scope) error {
	out.Name = in.Name
	out.IamInstanceProfile = in.IamInstanceProfile
	if err := Convert_v1alpha4_AWSResourceReference_To_v1alpha3_AWSResourceReference(&in.AMI, &out.AMI, s); err != nil {
		return err
	}
	out.ImageLookupFormat = in.ImageLookupFormat
	out.ImageLookupOrg = in.ImageLookupOrg
	out.ImageLookupBaseOS = in.ImageLookupBaseOS
	out.InstanceType = in.InstanceType
	out.RootVolume = (*clusterapiproviderawsapiv1alpha3.Volume)(unsafe.Pointer(in.RootVolume))
	out.SSHKeyName = (*string)(unsafe.Pointer(in.SSHKeyName))
	out.VersionNumber = (*int64)(unsafe.Pointer(in.VersionNumber))
	if in.AdditionalSecurityGroups != nil {
		in, out := &in.AdditionalSecurityGroups, &out.AdditionalSecurityGroups
		*out = make([]clusterapiproviderawsapiv1alpha3.AWSResourceReference, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_AWSResourceReference_To_v1alpha3_AWSResourceReference(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.AdditionalSecurityGroups = nil
	}
	return nil
}

// Convert_v1alpha4_AWSLaunchTemplate_To_v1alpha3_AWSLaunchTemplate is an autogenerated conversion function.
func Convert_v1alpha4_AWSLaunchTemplate_To_v1alpha3_AWSLaunchTemplate(in *v1alpha4.AWSLaunchTemplate, out *AWSLaunchTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSLaunchTemplate_To_v1alpha3_AWSLaunchTemplate(in, out, s)
}

func autoConvert_v1alpha3_AWSMachinePool_To_v1alpha4_AWSMachinePool(in *AWSMachinePool, out *v1alpha4.AWSMachinePool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_AWSMachinePoolSpec_To_v1alpha4_AWSMachinePoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_AWSMachinePoolStatus_To_v1alpha4_AWSMachinePoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AWSMachinePool_To_v1alpha4_AWSMachinePool is an autogenerated conversion function.
func Convert_v1alpha3_AWSMachinePool_To_v1alpha4_AWSMachinePool(in *AWSMachinePool, out *v1alpha4.AWSMachinePool, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSMachinePool_To_v1alpha4_AWSMachinePool(in, out, s)
}

func autoConvert_v1alpha4_AWSMachinePool_To_v1alpha3_AWSMachinePool(in *v1alpha4.AWSMachinePool, out *AWSMachinePool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AWSMachinePoolSpec_To_v1alpha3_AWSMachinePoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AWSMachinePoolStatus_To_v1alpha3_AWSMachinePoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AWSMachinePool_To_v1alpha3_AWSMachinePool is an autogenerated conversion function.
func Convert_v1alpha4_AWSMachinePool_To_v1alpha3_AWSMachinePool(in *v1alpha4.AWSMachinePool, out *AWSMachinePool, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSMachinePool_To_v1alpha3_AWSMachinePool(in, out, s)
}

func autoConvert_v1alpha3_AWSMachinePoolInstanceStatus_To_v1alpha4_AWSMachinePoolInstanceStatus(in *AWSMachinePoolInstanceStatus, out *v1alpha4.AWSMachinePoolInstanceStatus, s conversion.Scope) error {
	out.InstanceID = in.InstanceID
	out.Version = (*string)(unsafe.Pointer(in.Version))
	return nil
}

// Convert_v1alpha3_AWSMachinePoolInstanceStatus_To_v1alpha4_AWSMachinePoolInstanceStatus is an autogenerated conversion function.
func Convert_v1alpha3_AWSMachinePoolInstanceStatus_To_v1alpha4_AWSMachinePoolInstanceStatus(in *AWSMachinePoolInstanceStatus, out *v1alpha4.AWSMachinePoolInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSMachinePoolInstanceStatus_To_v1alpha4_AWSMachinePoolInstanceStatus(in, out, s)
}

func autoConvert_v1alpha4_AWSMachinePoolInstanceStatus_To_v1alpha3_AWSMachinePoolInstanceStatus(in *v1alpha4.AWSMachinePoolInstanceStatus, out *AWSMachinePoolInstanceStatus, s conversion.Scope) error {
	out.InstanceID = in.InstanceID
	out.Version = (*string)(unsafe.Pointer(in.Version))
	return nil
}

// Convert_v1alpha4_AWSMachinePoolInstanceStatus_To_v1alpha3_AWSMachinePoolInstanceStatus is an autogenerated conversion function.
func Convert_v1alpha4_AWSMachinePoolInstanceStatus_To_v1alpha3_AWSMachinePoolInstanceStatus(in *v1alpha4.AWSMachinePoolInstanceStatus, out *AWSMachinePoolInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSMachinePoolInstanceStatus_To_v1alpha3_AWSMachinePoolInstanceStatus(in, out, s)
}

func autoConvert_v1alpha3_AWSMachinePoolList_To_v1alpha4_AWSMachinePoolList(in *AWSMachinePoolList, out *v1alpha4.AWSMachinePoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.AWSMachinePool, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_AWSMachinePool_To_v1alpha4_AWSMachinePool(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_AWSMachinePoolList_To_v1alpha4_AWSMachinePoolList is an autogenerated conversion function.
func Convert_v1alpha3_AWSMachinePoolList_To_v1alpha4_AWSMachinePoolList(in *AWSMachinePoolList, out *v1alpha4.AWSMachinePoolList, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSMachinePoolList_To_v1alpha4_AWSMachinePoolList(in, out, s)
}

func autoConvert_v1alpha4_AWSMachinePoolList_To_v1alpha3_AWSMachinePoolList(in *v1alpha4.AWSMachinePoolList, out *AWSMachinePoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSMachinePool, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_AWSMachinePool_To_v1alpha3_AWSMachinePool(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_AWSMachinePoolList_To_v1alpha3_AWSMachinePoolList is an autogenerated conversion function.
func Convert_v1alpha4_AWSMachinePoolList_To_v1alpha3_AWSMachinePoolList(in *v1alpha4.AWSMachinePoolList, out *AWSMachinePoolList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSMachinePoolList_To_v1alpha3_AWSMachinePoolList(in, out, s)
}

func autoConvert_v1alpha3_AWSMachinePoolSpec_To_v1alpha4_AWSMachinePoolSpec(in *AWSMachinePoolSpec, out *v1alpha4.AWSMachinePoolSpec, s conversion.Scope) error {
	out.ProviderID = in.ProviderID
	out.MinSize = in.MinSize
	out.MaxSize = in.MaxSize
	out.AvailabilityZones = *(*[]string)(unsafe.Pointer(&in.AvailabilityZones))
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]clusterapiproviderawsapiv1alpha4.AWSResourceReference, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_AWSResourceReference_To_v1alpha4_AWSResourceReference(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Subnets = nil
	}
	out.AdditionalTags = *(*clusterapiproviderawsapiv1alpha4.Tags)(unsafe.Pointer(&in.AdditionalTags))
	if err := Convert_v1alpha3_AWSLaunchTemplate_To_v1alpha4_AWSLaunchTemplate(&in.AWSLaunchTemplate, &out.AWSLaunchTemplate, s); err != nil {
		return err
	}
	out.MixedInstancesPolicy = (*v1alpha4.MixedInstancesPolicy)(unsafe.Pointer(in.MixedInstancesPolicy))
	out.ProviderIDList = *(*[]string)(unsafe.Pointer(&in.ProviderIDList))
	out.DefaultCoolDown = in.DefaultCoolDown
	out.RefreshPreferences = (*v1alpha4.RefreshPreferences)(unsafe.Pointer(in.RefreshPreferences))
	out.CapacityRebalance = in.CapacityRebalance
	return nil
}

// Convert_v1alpha3_AWSMachinePoolSpec_To_v1alpha4_AWSMachinePoolSpec is an autogenerated conversion function.
func Convert_v1alpha3_AWSMachinePoolSpec_To_v1alpha4_AWSMachinePoolSpec(in *AWSMachinePoolSpec, out *v1alpha4.AWSMachinePoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSMachinePoolSpec_To_v1alpha4_AWSMachinePoolSpec(in, out, s)
}

func autoConvert_v1alpha4_AWSMachinePoolSpec_To_v1alpha3_AWSMachinePoolSpec(in *v1alpha4.AWSMachinePoolSpec, out *AWSMachinePoolSpec, s conversion.Scope) error {
	out.ProviderID = in.ProviderID
	out.MinSize = in.MinSize
	out.MaxSize = in.MaxSize
	out.AvailabilityZones = *(*[]string)(unsafe.Pointer(&in.AvailabilityZones))
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]clusterapiproviderawsapiv1alpha3.AWSResourceReference, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_AWSResourceReference_To_v1alpha3_AWSResourceReference(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Subnets = nil
	}
	out.AdditionalTags = *(*clusterapiproviderawsapiv1alpha3.Tags)(unsafe.Pointer(&in.AdditionalTags))
	if err := Convert_v1alpha4_AWSLaunchTemplate_To_v1alpha3_AWSLaunchTemplate(&in.AWSLaunchTemplate, &out.AWSLaunchTemplate, s); err != nil {
		return err
	}
	out.MixedInstancesPolicy = (*MixedInstancesPolicy)(unsafe.Pointer(in.MixedInstancesPolicy))
	out.ProviderIDList = *(*[]string)(unsafe.Pointer(&in.ProviderIDList))
	out.DefaultCoolDown = in.DefaultCoolDown
	out.RefreshPreferences = (*RefreshPreferences)(unsafe.Pointer(in.RefreshPreferences))
	out.CapacityRebalance = in.CapacityRebalance
	return nil
}

// Convert_v1alpha4_AWSMachinePoolSpec_To_v1alpha3_AWSMachinePoolSpec is an autogenerated conversion function.
func Convert_v1alpha4_AWSMachinePoolSpec_To_v1alpha3_AWSMachinePoolSpec(in *v1alpha4.AWSMachinePoolSpec, out *AWSMachinePoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSMachinePoolSpec_To_v1alpha3_AWSMachinePoolSpec(in, out, s)
}

func autoConvert_v1alpha3_AWSMachinePoolStatus_To_v1alpha4_AWSMachinePoolStatus(in *AWSMachinePoolStatus, out *v1alpha4.AWSMachinePoolStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	out.Instances = *(*[]v1alpha4.AWSMachinePoolInstanceStatus)(unsafe.Pointer(&in.Instances))
	out.LaunchTemplateID = in.LaunchTemplateID
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.ASGStatus = (*v1alpha4.ASGStatus)(unsafe.Pointer(in.ASGStatus))
	return nil
}

// Convert_v1alpha3_AWSMachinePoolStatus_To_v1alpha4_AWSMachinePoolStatus is an autogenerated conversion function.
func Convert_v1alpha3_AWSMachinePoolStatus_To_v1alpha4_AWSMachinePoolStatus(in *AWSMachinePoolStatus, out *v1alpha4.AWSMachinePoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSMachinePoolStatus_To_v1alpha4_AWSMachinePoolStatus(in, out, s)
}

func autoConvert_v1alpha4_AWSMachinePoolStatus_To_v1alpha3_AWSMachinePoolStatus(in *v1alpha4.AWSMachinePoolStatus, out *AWSMachinePoolStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.Conditions = *(*apiv1alpha3.Conditions)(unsafe.Pointer(&in.Conditions))
	out.Instances = *(*[]AWSMachinePoolInstanceStatus)(unsafe.Pointer(&in.Instances))
	out.LaunchTemplateID = in.LaunchTemplateID
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.ASGStatus = (*ASGStatus)(unsafe.Pointer(in.ASGStatus))
	return nil
}

// Convert_v1alpha4_AWSMachinePoolStatus_To_v1alpha3_AWSMachinePoolStatus is an autogenerated conversion function.
func Convert_v1alpha4_AWSMachinePoolStatus_To_v1alpha3_AWSMachinePoolStatus(in *v1alpha4.AWSMachinePoolStatus, out *AWSMachinePoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSMachinePoolStatus_To_v1alpha3_AWSMachinePoolStatus(in, out, s)
}

func autoConvert_v1alpha3_AWSManagedCluster_To_v1alpha4_AWSManagedCluster(in *AWSManagedCluster, out *v1alpha4.AWSManagedCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_AWSManagedClusterSpec_To_v1alpha4_AWSManagedClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_AWSManagedClusterStatus_To_v1alpha4_AWSManagedClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AWSManagedCluster_To_v1alpha4_AWSManagedCluster is an autogenerated conversion function.
func Convert_v1alpha3_AWSManagedCluster_To_v1alpha4_AWSManagedCluster(in *AWSManagedCluster, out *v1alpha4.AWSManagedCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSManagedCluster_To_v1alpha4_AWSManagedCluster(in, out, s)
}

func autoConvert_v1alpha4_AWSManagedCluster_To_v1alpha3_AWSManagedCluster(in *v1alpha4.AWSManagedCluster, out *AWSManagedCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AWSManagedClusterSpec_To_v1alpha3_AWSManagedClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AWSManagedClusterStatus_To_v1alpha3_AWSManagedClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AWSManagedCluster_To_v1alpha3_AWSManagedCluster is an autogenerated conversion function.
func Convert_v1alpha4_AWSManagedCluster_To_v1alpha3_AWSManagedCluster(in *v1alpha4.AWSManagedCluster, out *AWSManagedCluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSManagedCluster_To_v1alpha3_AWSManagedCluster(in, out, s)
}

func autoConvert_v1alpha3_AWSManagedClusterList_To_v1alpha4_AWSManagedClusterList(in *AWSManagedClusterList, out *v1alpha4.AWSManagedClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.AWSManagedCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_AWSManagedCluster_To_v1alpha4_AWSManagedCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_AWSManagedClusterList_To_v1alpha4_AWSManagedClusterList is an autogenerated conversion function.
func Convert_v1alpha3_AWSManagedClusterList_To_v1alpha4_AWSManagedClusterList(in *AWSManagedClusterList, out *v1alpha4.AWSManagedClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSManagedClusterList_To_v1alpha4_AWSManagedClusterList(in, out, s)
}

func autoConvert_v1alpha4_AWSManagedClusterList_To_v1alpha3_AWSManagedClusterList(in *v1alpha4.AWSManagedClusterList, out *AWSManagedClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSManagedCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_AWSManagedCluster_To_v1alpha3_AWSManagedCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_AWSManagedClusterList_To_v1alpha3_AWSManagedClusterList is an autogenerated conversion function.
func Convert_v1alpha4_AWSManagedClusterList_To_v1alpha3_AWSManagedClusterList(in *v1alpha4.AWSManagedClusterList, out *AWSManagedClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSManagedClusterList_To_v1alpha3_AWSManagedClusterList(in, out, s)
}

func autoConvert_v1alpha3_AWSManagedClusterSpec_To_v1alpha4_AWSManagedClusterSpec(in *AWSManagedClusterSpec, out *v1alpha4.AWSManagedClusterSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AWSManagedClusterSpec_To_v1alpha4_AWSManagedClusterSpec is an autogenerated conversion function.
func Convert_v1alpha3_AWSManagedClusterSpec_To_v1alpha4_AWSManagedClusterSpec(in *AWSManagedClusterSpec, out *v1alpha4.AWSManagedClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSManagedClusterSpec_To_v1alpha4_AWSManagedClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_AWSManagedClusterSpec_To_v1alpha3_AWSManagedClusterSpec(in *v1alpha4.AWSManagedClusterSpec, out *AWSManagedClusterSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AWSManagedClusterSpec_To_v1alpha3_AWSManagedClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_AWSManagedClusterSpec_To_v1alpha3_AWSManagedClusterSpec(in *v1alpha4.AWSManagedClusterSpec, out *AWSManagedClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSManagedClusterSpec_To_v1alpha3_AWSManagedClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_AWSManagedClusterStatus_To_v1alpha4_AWSManagedClusterStatus(in *AWSManagedClusterStatus, out *v1alpha4.AWSManagedClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureDomains = *(*apiv1alpha4.FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	return nil
}

// Convert_v1alpha3_AWSManagedClusterStatus_To_v1alpha4_AWSManagedClusterStatus is an autogenerated conversion function.
func Convert_v1alpha3_AWSManagedClusterStatus_To_v1alpha4_AWSManagedClusterStatus(in *AWSManagedClusterStatus, out *v1alpha4.AWSManagedClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSManagedClusterStatus_To_v1alpha4_AWSManagedClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_AWSManagedClusterStatus_To_v1alpha3_AWSManagedClusterStatus(in *v1alpha4.AWSManagedClusterStatus, out *AWSManagedClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureDomains = *(*apiv1alpha3.FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	return nil
}

// Convert_v1alpha4_AWSManagedClusterStatus_To_v1alpha3_AWSManagedClusterStatus is an autogenerated conversion function.
func Convert_v1alpha4_AWSManagedClusterStatus_To_v1alpha3_AWSManagedClusterStatus(in *v1alpha4.AWSManagedClusterStatus, out *AWSManagedClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSManagedClusterStatus_To_v1alpha3_AWSManagedClusterStatus(in, out, s)
}

func autoConvert_v1alpha3_AWSManagedMachinePool_To_v1alpha4_AWSManagedMachinePool(in *AWSManagedMachinePool, out *v1alpha4.AWSManagedMachinePool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_AWSManagedMachinePoolSpec_To_v1alpha4_AWSManagedMachinePoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_AWSManagedMachinePoolStatus_To_v1alpha4_AWSManagedMachinePoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_AWSManagedMachinePool_To_v1alpha4_AWSManagedMachinePool is an autogenerated conversion function.
func Convert_v1alpha3_AWSManagedMachinePool_To_v1alpha4_AWSManagedMachinePool(in *AWSManagedMachinePool, out *v1alpha4.AWSManagedMachinePool, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSManagedMachinePool_To_v1alpha4_AWSManagedMachinePool(in, out, s)
}

func autoConvert_v1alpha4_AWSManagedMachinePool_To_v1alpha3_AWSManagedMachinePool(in *v1alpha4.AWSManagedMachinePool, out *AWSManagedMachinePool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_AWSManagedMachinePoolSpec_To_v1alpha3_AWSManagedMachinePoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_AWSManagedMachinePoolStatus_To_v1alpha3_AWSManagedMachinePoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_AWSManagedMachinePool_To_v1alpha3_AWSManagedMachinePool is an autogenerated conversion function.
func Convert_v1alpha4_AWSManagedMachinePool_To_v1alpha3_AWSManagedMachinePool(in *v1alpha4.AWSManagedMachinePool, out *AWSManagedMachinePool, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSManagedMachinePool_To_v1alpha3_AWSManagedMachinePool(in, out, s)
}

func autoConvert_v1alpha3_AWSManagedMachinePoolList_To_v1alpha4_AWSManagedMachinePoolList(in *AWSManagedMachinePoolList, out *v1alpha4.AWSManagedMachinePoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.AWSManagedMachinePool, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_AWSManagedMachinePool_To_v1alpha4_AWSManagedMachinePool(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_AWSManagedMachinePoolList_To_v1alpha4_AWSManagedMachinePoolList is an autogenerated conversion function.
func Convert_v1alpha3_AWSManagedMachinePoolList_To_v1alpha4_AWSManagedMachinePoolList(in *AWSManagedMachinePoolList, out *v1alpha4.AWSManagedMachinePoolList, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSManagedMachinePoolList_To_v1alpha4_AWSManagedMachinePoolList(in, out, s)
}

func autoConvert_v1alpha4_AWSManagedMachinePoolList_To_v1alpha3_AWSManagedMachinePoolList(in *v1alpha4.AWSManagedMachinePoolList, out *AWSManagedMachinePoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSManagedMachinePool, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_AWSManagedMachinePool_To_v1alpha3_AWSManagedMachinePool(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_AWSManagedMachinePoolList_To_v1alpha3_AWSManagedMachinePoolList is an autogenerated conversion function.
func Convert_v1alpha4_AWSManagedMachinePoolList_To_v1alpha3_AWSManagedMachinePoolList(in *v1alpha4.AWSManagedMachinePoolList, out *AWSManagedMachinePoolList, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSManagedMachinePoolList_To_v1alpha3_AWSManagedMachinePoolList(in, out, s)
}

func autoConvert_v1alpha3_AWSManagedMachinePoolSpec_To_v1alpha4_AWSManagedMachinePoolSpec(in *AWSManagedMachinePoolSpec, out *v1alpha4.AWSManagedMachinePoolSpec, s conversion.Scope) error {
	out.EKSNodegroupName = in.EKSNodegroupName
	out.AvailabilityZones = *(*[]string)(unsafe.Pointer(&in.AvailabilityZones))
	out.SubnetIDs = *(*[]string)(unsafe.Pointer(&in.SubnetIDs))
	out.AdditionalTags = *(*clusterapiproviderawsapiv1alpha4.Tags)(unsafe.Pointer(&in.AdditionalTags))
	out.RoleName = in.RoleName
	out.AMIVersion = (*string)(unsafe.Pointer(in.AMIVersion))
	out.AMIType = (*v1alpha4.ManagedMachineAMIType)(unsafe.Pointer(in.AMIType))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.DiskSize = (*int32)(unsafe.Pointer(in.DiskSize))
	out.InstanceType = (*string)(unsafe.Pointer(in.InstanceType))
	out.Scaling = (*v1alpha4.ManagedMachinePoolScaling)(unsafe.Pointer(in.Scaling))
	out.RemoteAccess = (*v1alpha4.ManagedRemoteAccess)(unsafe.Pointer(in.RemoteAccess))
	out.ProviderIDList = *(*[]string)(unsafe.Pointer(&in.ProviderIDList))
	return nil
}

// Convert_v1alpha3_AWSManagedMachinePoolSpec_To_v1alpha4_AWSManagedMachinePoolSpec is an autogenerated conversion function.
func Convert_v1alpha3_AWSManagedMachinePoolSpec_To_v1alpha4_AWSManagedMachinePoolSpec(in *AWSManagedMachinePoolSpec, out *v1alpha4.AWSManagedMachinePoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSManagedMachinePoolSpec_To_v1alpha4_AWSManagedMachinePoolSpec(in, out, s)
}

func autoConvert_v1alpha4_AWSManagedMachinePoolSpec_To_v1alpha3_AWSManagedMachinePoolSpec(in *v1alpha4.AWSManagedMachinePoolSpec, out *AWSManagedMachinePoolSpec, s conversion.Scope) error {
	out.EKSNodegroupName = in.EKSNodegroupName
	out.AvailabilityZones = *(*[]string)(unsafe.Pointer(&in.AvailabilityZones))
	out.SubnetIDs = *(*[]string)(unsafe.Pointer(&in.SubnetIDs))
	out.AdditionalTags = *(*clusterapiproviderawsapiv1alpha3.Tags)(unsafe.Pointer(&in.AdditionalTags))
	out.RoleName = in.RoleName
	out.AMIVersion = (*string)(unsafe.Pointer(in.AMIVersion))
	out.AMIType = (*ManagedMachineAMIType)(unsafe.Pointer(in.AMIType))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	// WARNING: in.Taints requires manual conversion: does not exist in peer-type
	out.DiskSize = (*int32)(unsafe.Pointer(in.DiskSize))
	out.InstanceType = (*string)(unsafe.Pointer(in.InstanceType))
	out.Scaling = (*ManagedMachinePoolScaling)(unsafe.Pointer(in.Scaling))
	out.RemoteAccess = (*ManagedRemoteAccess)(unsafe.Pointer(in.RemoteAccess))
	out.ProviderIDList = *(*[]string)(unsafe.Pointer(&in.ProviderIDList))
	return nil
}

func autoConvert_v1alpha3_AWSManagedMachinePoolStatus_To_v1alpha4_AWSManagedMachinePoolStatus(in *AWSManagedMachinePoolStatus, out *v1alpha4.AWSManagedMachinePoolStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha3_AWSManagedMachinePoolStatus_To_v1alpha4_AWSManagedMachinePoolStatus is an autogenerated conversion function.
func Convert_v1alpha3_AWSManagedMachinePoolStatus_To_v1alpha4_AWSManagedMachinePoolStatus(in *AWSManagedMachinePoolStatus, out *v1alpha4.AWSManagedMachinePoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_AWSManagedMachinePoolStatus_To_v1alpha4_AWSManagedMachinePoolStatus(in, out, s)
}

func autoConvert_v1alpha4_AWSManagedMachinePoolStatus_To_v1alpha3_AWSManagedMachinePoolStatus(in *v1alpha4.AWSManagedMachinePoolStatus, out *AWSManagedMachinePoolStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1alpha3.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha4_AWSManagedMachinePoolStatus_To_v1alpha3_AWSManagedMachinePoolStatus is an autogenerated conversion function.
func Convert_v1alpha4_AWSManagedMachinePoolStatus_To_v1alpha3_AWSManagedMachinePoolStatus(in *v1alpha4.AWSManagedMachinePoolStatus, out *AWSManagedMachinePoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_AWSManagedMachinePoolStatus_To_v1alpha3_AWSManagedMachinePoolStatus(in, out, s)
}

func autoConvert_v1alpha3_AutoScalingGroup_To_v1alpha4_AutoScalingGroup(in *AutoScalingGroup, out *v1alpha4.AutoScalingGroup, s conversion.Scope) error {
	out.ID = in.ID
	out.Tags = *(*clusterapiproviderawsapiv1alpha4.Tags)(unsafe.Pointer(&in.Tags))
	out.Name = in.Name
	out.DesiredCapacity = (*int32)(unsafe.Pointer(in.DesiredCapacity))
	out.MaxSize = in.MaxSize
	out.MinSize = in.MinSize
	out.PlacementGroup = in.PlacementGroup
	out.Subnets = *(*[]string)(unsafe.Pointer(&in.Subnets))
	out.DefaultCoolDown = in.DefaultCoolDown
	out.CapacityRebalance = in.CapacityRebalance
	out.MixedInstancesPolicy = (*v1alpha4.MixedInstancesPolicy)(unsafe.Pointer(in.MixedInstancesPolicy))
	out.Status = v1alpha4.ASGStatus(in.Status)
	out.Instances = *(*[]clusterapiproviderawsapiv1alpha4.Instance)(unsafe.Pointer(&in.Instances))
	return nil
}

// Convert_v1alpha3_AutoScalingGroup_To_v1alpha4_AutoScalingGroup is an autogenerated conversion function.
func Convert_v1alpha3_AutoScalingGroup_To_v1alpha4_AutoScalingGroup(in *AutoScalingGroup, out *v1alpha4.AutoScalingGroup, s conversion.Scope) error {
	return autoConvert_v1alpha3_AutoScalingGroup_To_v1alpha4_AutoScalingGroup(in, out, s)
}

func autoConvert_v1alpha4_AutoScalingGroup_To_v1alpha3_AutoScalingGroup(in *v1alpha4.AutoScalingGroup, out *AutoScalingGroup, s conversion.Scope) error {
	out.ID = in.ID
	out.Tags = *(*clusterapiproviderawsapiv1alpha3.Tags)(unsafe.Pointer(&in.Tags))
	out.Name = in.Name
	out.DesiredCapacity = (*int32)(unsafe.Pointer(in.DesiredCapacity))
	out.MaxSize = in.MaxSize
	out.MinSize = in.MinSize
	out.PlacementGroup = in.PlacementGroup
	out.Subnets = *(*[]string)(unsafe.Pointer(&in.Subnets))
	out.DefaultCoolDown = in.DefaultCoolDown
	out.CapacityRebalance = in.CapacityRebalance
	out.MixedInstancesPolicy = (*MixedInstancesPolicy)(unsafe.Pointer(in.MixedInstancesPolicy))
	out.Status = ASGStatus(in.Status)
	out.Instances = *(*[]clusterapiproviderawsapiv1alpha3.Instance)(unsafe.Pointer(&in.Instances))
	return nil
}

// Convert_v1alpha4_AutoScalingGroup_To_v1alpha3_AutoScalingGroup is an autogenerated conversion function.
func Convert_v1alpha4_AutoScalingGroup_To_v1alpha3_AutoScalingGroup(in *v1alpha4.AutoScalingGroup, out *AutoScalingGroup, s conversion.Scope) error {
	return autoConvert_v1alpha4_AutoScalingGroup_To_v1alpha3_AutoScalingGroup(in, out, s)
}

func autoConvert_v1alpha3_BlockDeviceMapping_To_v1alpha4_BlockDeviceMapping(in *BlockDeviceMapping, out *v1alpha4.BlockDeviceMapping, s conversion.Scope) error {
	out.DeviceName = in.DeviceName
	if err := Convert_v1alpha3_EBS_To_v1alpha4_EBS(&in.Ebs, &out.Ebs, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_BlockDeviceMapping_To_v1alpha4_BlockDeviceMapping is an autogenerated conversion function.
func Convert_v1alpha3_BlockDeviceMapping_To_v1alpha4_BlockDeviceMapping(in *BlockDeviceMapping, out *v1alpha4.BlockDeviceMapping, s conversion.Scope) error {
	return autoConvert_v1alpha3_BlockDeviceMapping_To_v1alpha4_BlockDeviceMapping(in, out, s)
}

func autoConvert_v1alpha4_BlockDeviceMapping_To_v1alpha3_BlockDeviceMapping(in *v1alpha4.BlockDeviceMapping, out *BlockDeviceMapping, s conversion.Scope) error {
	out.DeviceName = in.DeviceName
	if err := Convert_v1alpha4_EBS_To_v1alpha3_EBS(&in.Ebs, &out.Ebs, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_BlockDeviceMapping_To_v1alpha3_BlockDeviceMapping is an autogenerated conversion function.
func Convert_v1alpha4_BlockDeviceMapping_To_v1alpha3_BlockDeviceMapping(in *v1alpha4.BlockDeviceMapping, out *BlockDeviceMapping, s conversion.Scope) error {
	return autoConvert_v1alpha4_BlockDeviceMapping_To_v1alpha3_BlockDeviceMapping(in, out, s)
}

func autoConvert_v1alpha3_EBS_To_v1alpha4_EBS(in *EBS, out *v1alpha4.EBS, s conversion.Scope) error {
	out.Encrypted = in.Encrypted
	out.VolumeSize = in.VolumeSize
	out.VolumeType = in.VolumeType
	return nil
}

// Convert_v1alpha3_EBS_To_v1alpha4_EBS is an autogenerated conversion function.
func Convert_v1alpha3_EBS_To_v1alpha4_EBS(in *EBS, out *v1alpha4.EBS, s conversion.Scope) error {
	return autoConvert_v1alpha3_EBS_To_v1alpha4_EBS(in, out, s)
}

func autoConvert_v1alpha4_EBS_To_v1alpha3_EBS(in *v1alpha4.EBS, out *EBS, s conversion.Scope) error {
	out.Encrypted = in.Encrypted
	out.VolumeSize = in.VolumeSize
	out.VolumeType = in.VolumeType
	return nil
}

// Convert_v1alpha4_EBS_To_v1alpha3_EBS is an autogenerated conversion function.
func Convert_v1alpha4_EBS_To_v1alpha3_EBS(in *v1alpha4.EBS, out *EBS, s conversion.Scope) error {
	return autoConvert_v1alpha4_EBS_To_v1alpha3_EBS(in, out, s)
}

func autoConvert_v1alpha3_FargateProfileSpec_To_v1alpha4_FargateProfileSpec(in *FargateProfileSpec, out *v1alpha4.FargateProfileSpec, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.ProfileName = in.ProfileName
	out.SubnetIDs = *(*[]string)(unsafe.Pointer(&in.SubnetIDs))
	out.AdditionalTags = *(*clusterapiproviderawsapiv1alpha4.Tags)(unsafe.Pointer(&in.AdditionalTags))
	out.RoleName = in.RoleName
	out.Selectors = *(*[]v1alpha4.FargateSelector)(unsafe.Pointer(&in.Selectors))
	return nil
}

// Convert_v1alpha3_FargateProfileSpec_To_v1alpha4_FargateProfileSpec is an autogenerated conversion function.
func Convert_v1alpha3_FargateProfileSpec_To_v1alpha4_FargateProfileSpec(in *FargateProfileSpec, out *v1alpha4.FargateProfileSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_FargateProfileSpec_To_v1alpha4_FargateProfileSpec(in, out, s)
}

func autoConvert_v1alpha4_FargateProfileSpec_To_v1alpha3_FargateProfileSpec(in *v1alpha4.FargateProfileSpec, out *FargateProfileSpec, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.ProfileName = in.ProfileName
	out.SubnetIDs = *(*[]string)(unsafe.Pointer(&in.SubnetIDs))
	out.AdditionalTags = *(*clusterapiproviderawsapiv1alpha3.Tags)(unsafe.Pointer(&in.AdditionalTags))
	out.RoleName = in.RoleName
	out.Selectors = *(*[]FargateSelector)(unsafe.Pointer(&in.Selectors))
	return nil
}

// Convert_v1alpha4_FargateProfileSpec_To_v1alpha3_FargateProfileSpec is an autogenerated conversion function.
func Convert_v1alpha4_FargateProfileSpec_To_v1alpha3_FargateProfileSpec(in *v1alpha4.FargateProfileSpec, out *FargateProfileSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_FargateProfileSpec_To_v1alpha3_FargateProfileSpec(in, out, s)
}

func autoConvert_v1alpha3_FargateProfileStatus_To_v1alpha4_FargateProfileStatus(in *FargateProfileStatus, out *v1alpha4.FargateProfileStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha3_FargateProfileStatus_To_v1alpha4_FargateProfileStatus is an autogenerated conversion function.
func Convert_v1alpha3_FargateProfileStatus_To_v1alpha4_FargateProfileStatus(in *FargateProfileStatus, out *v1alpha4.FargateProfileStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_FargateProfileStatus_To_v1alpha4_FargateProfileStatus(in, out, s)
}

func autoConvert_v1alpha4_FargateProfileStatus_To_v1alpha3_FargateProfileStatus(in *v1alpha4.FargateProfileStatus, out *FargateProfileStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1alpha3.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha4_FargateProfileStatus_To_v1alpha3_FargateProfileStatus is an autogenerated conversion function.
func Convert_v1alpha4_FargateProfileStatus_To_v1alpha3_FargateProfileStatus(in *v1alpha4.FargateProfileStatus, out *FargateProfileStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_FargateProfileStatus_To_v1alpha3_FargateProfileStatus(in, out, s)
}

func autoConvert_v1alpha3_FargateSelector_To_v1alpha4_FargateSelector(in *FargateSelector, out *v1alpha4.FargateSelector, s conversion.Scope) error {
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha3_FargateSelector_To_v1alpha4_FargateSelector is an autogenerated conversion function.
func Convert_v1alpha3_FargateSelector_To_v1alpha4_FargateSelector(in *FargateSelector, out *v1alpha4.FargateSelector, s conversion.Scope) error {
	return autoConvert_v1alpha3_FargateSelector_To_v1alpha4_FargateSelector(in, out, s)
}

func autoConvert_v1alpha4_FargateSelector_To_v1alpha3_FargateSelector(in *v1alpha4.FargateSelector, out *FargateSelector, s conversion.Scope) error {
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha4_FargateSelector_To_v1alpha3_FargateSelector is an autogenerated conversion function.
func Convert_v1alpha4_FargateSelector_To_v1alpha3_FargateSelector(in *v1alpha4.FargateSelector, out *FargateSelector, s conversion.Scope) error {
	return autoConvert_v1alpha4_FargateSelector_To_v1alpha3_FargateSelector(in, out, s)
}

func autoConvert_v1alpha3_InstancesDistribution_To_v1alpha4_InstancesDistribution(in *InstancesDistribution, out *v1alpha4.InstancesDistribution, s conversion.Scope) error {
	out.OnDemandAllocationStrategy = v1alpha4.OnDemandAllocationStrategy(in.OnDemandAllocationStrategy)
	out.SpotAllocationStrategy = v1alpha4.SpotAllocationStrategy(in.SpotAllocationStrategy)
	out.OnDemandBaseCapacity = (*int64)(unsafe.Pointer(in.OnDemandBaseCapacity))
	out.OnDemandPercentageAboveBaseCapacity = (*int64)(unsafe.Pointer(in.OnDemandPercentageAboveBaseCapacity))
	return nil
}

// Convert_v1alpha3_InstancesDistribution_To_v1alpha4_InstancesDistribution is an autogenerated conversion function.
func Convert_v1alpha3_InstancesDistribution_To_v1alpha4_InstancesDistribution(in *InstancesDistribution, out *v1alpha4.InstancesDistribution, s conversion.Scope) error {
	return autoConvert_v1alpha3_InstancesDistribution_To_v1alpha4_InstancesDistribution(in, out, s)
}

func autoConvert_v1alpha4_InstancesDistribution_To_v1alpha3_InstancesDistribution(in *v1alpha4.InstancesDistribution, out *InstancesDistribution, s conversion.Scope) error {
	out.OnDemandAllocationStrategy = OnDemandAllocationStrategy(in.OnDemandAllocationStrategy)
	out.SpotAllocationStrategy = SpotAllocationStrategy(in.SpotAllocationStrategy)
	out.OnDemandBaseCapacity = (*int64)(unsafe.Pointer(in.OnDemandBaseCapacity))
	out.OnDemandPercentageAboveBaseCapacity = (*int64)(unsafe.Pointer(in.OnDemandPercentageAboveBaseCapacity))
	return nil
}

// Convert_v1alpha4_InstancesDistribution_To_v1alpha3_InstancesDistribution is an autogenerated conversion function.
func Convert_v1alpha4_InstancesDistribution_To_v1alpha3_InstancesDistribution(in *v1alpha4.InstancesDistribution, out *InstancesDistribution, s conversion.Scope) error {
	return autoConvert_v1alpha4_InstancesDistribution_To_v1alpha3_InstancesDistribution(in, out, s)
}

func autoConvert_v1alpha3_ManagedMachinePoolScaling_To_v1alpha4_ManagedMachinePoolScaling(in *ManagedMachinePoolScaling, out *v1alpha4.ManagedMachinePoolScaling, s conversion.Scope) error {
	out.MinSize = (*int32)(unsafe.Pointer(in.MinSize))
	out.MaxSize = (*int32)(unsafe.Pointer(in.MaxSize))
	return nil
}

// Convert_v1alpha3_ManagedMachinePoolScaling_To_v1alpha4_ManagedMachinePoolScaling is an autogenerated conversion function.
func Convert_v1alpha3_ManagedMachinePoolScaling_To_v1alpha4_ManagedMachinePoolScaling(in *ManagedMachinePoolScaling, out *v1alpha4.ManagedMachinePoolScaling, s conversion.Scope) error {
	return autoConvert_v1alpha3_ManagedMachinePoolScaling_To_v1alpha4_ManagedMachinePoolScaling(in, out, s)
}

func autoConvert_v1alpha4_ManagedMachinePoolScaling_To_v1alpha3_ManagedMachinePoolScaling(in *v1alpha4.ManagedMachinePoolScaling, out *ManagedMachinePoolScaling, s conversion.Scope) error {
	out.MinSize = (*int32)(unsafe.Pointer(in.MinSize))
	out.MaxSize = (*int32)(unsafe.Pointer(in.MaxSize))
	return nil
}

// Convert_v1alpha4_ManagedMachinePoolScaling_To_v1alpha3_ManagedMachinePoolScaling is an autogenerated conversion function.
func Convert_v1alpha4_ManagedMachinePoolScaling_To_v1alpha3_ManagedMachinePoolScaling(in *v1alpha4.ManagedMachinePoolScaling, out *ManagedMachinePoolScaling, s conversion.Scope) error {
	return autoConvert_v1alpha4_ManagedMachinePoolScaling_To_v1alpha3_ManagedMachinePoolScaling(in, out, s)
}

func autoConvert_v1alpha3_ManagedRemoteAccess_To_v1alpha4_ManagedRemoteAccess(in *ManagedRemoteAccess, out *v1alpha4.ManagedRemoteAccess, s conversion.Scope) error {
	out.SSHKeyName = (*string)(unsafe.Pointer(in.SSHKeyName))
	out.SourceSecurityGroups = *(*[]string)(unsafe.Pointer(&in.SourceSecurityGroups))
	out.Public = in.Public
	return nil
}

// Convert_v1alpha3_ManagedRemoteAccess_To_v1alpha4_ManagedRemoteAccess is an autogenerated conversion function.
func Convert_v1alpha3_ManagedRemoteAccess_To_v1alpha4_ManagedRemoteAccess(in *ManagedRemoteAccess, out *v1alpha4.ManagedRemoteAccess, s conversion.Scope) error {
	return autoConvert_v1alpha3_ManagedRemoteAccess_To_v1alpha4_ManagedRemoteAccess(in, out, s)
}

func autoConvert_v1alpha4_ManagedRemoteAccess_To_v1alpha3_ManagedRemoteAccess(in *v1alpha4.ManagedRemoteAccess, out *ManagedRemoteAccess, s conversion.Scope) error {
	out.SSHKeyName = (*string)(unsafe.Pointer(in.SSHKeyName))
	out.SourceSecurityGroups = *(*[]string)(unsafe.Pointer(&in.SourceSecurityGroups))
	out.Public = in.Public
	return nil
}

// Convert_v1alpha4_ManagedRemoteAccess_To_v1alpha3_ManagedRemoteAccess is an autogenerated conversion function.
func Convert_v1alpha4_ManagedRemoteAccess_To_v1alpha3_ManagedRemoteAccess(in *v1alpha4.ManagedRemoteAccess, out *ManagedRemoteAccess, s conversion.Scope) error {
	return autoConvert_v1alpha4_ManagedRemoteAccess_To_v1alpha3_ManagedRemoteAccess(in, out, s)
}

func autoConvert_v1alpha3_MixedInstancesPolicy_To_v1alpha4_MixedInstancesPolicy(in *MixedInstancesPolicy, out *v1alpha4.MixedInstancesPolicy, s conversion.Scope) error {
	out.InstancesDistribution = (*v1alpha4.InstancesDistribution)(unsafe.Pointer(in.InstancesDistribution))
	out.Overrides = *(*[]v1alpha4.Overrides)(unsafe.Pointer(&in.Overrides))
	return nil
}

// Convert_v1alpha3_MixedInstancesPolicy_To_v1alpha4_MixedInstancesPolicy is an autogenerated conversion function.
func Convert_v1alpha3_MixedInstancesPolicy_To_v1alpha4_MixedInstancesPolicy(in *MixedInstancesPolicy, out *v1alpha4.MixedInstancesPolicy, s conversion.Scope) error {
	return autoConvert_v1alpha3_MixedInstancesPolicy_To_v1alpha4_MixedInstancesPolicy(in, out, s)
}

func autoConvert_v1alpha4_MixedInstancesPolicy_To_v1alpha3_MixedInstancesPolicy(in *v1alpha4.MixedInstancesPolicy, out *MixedInstancesPolicy, s conversion.Scope) error {
	out.InstancesDistribution = (*InstancesDistribution)(unsafe.Pointer(in.InstancesDistribution))
	out.Overrides = *(*[]Overrides)(unsafe.Pointer(&in.Overrides))
	return nil
}

// Convert_v1alpha4_MixedInstancesPolicy_To_v1alpha3_MixedInstancesPolicy is an autogenerated conversion function.
func Convert_v1alpha4_MixedInstancesPolicy_To_v1alpha3_MixedInstancesPolicy(in *v1alpha4.MixedInstancesPolicy, out *MixedInstancesPolicy, s conversion.Scope) error {
	return autoConvert_v1alpha4_MixedInstancesPolicy_To_v1alpha3_MixedInstancesPolicy(in, out, s)
}

func autoConvert_v1alpha3_Overrides_To_v1alpha4_Overrides(in *Overrides, out *v1alpha4.Overrides, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	return nil
}

// Convert_v1alpha3_Overrides_To_v1alpha4_Overrides is an autogenerated conversion function.
func Convert_v1alpha3_Overrides_To_v1alpha4_Overrides(in *Overrides, out *v1alpha4.Overrides, s conversion.Scope) error {
	return autoConvert_v1alpha3_Overrides_To_v1alpha4_Overrides(in, out, s)
}

func autoConvert_v1alpha4_Overrides_To_v1alpha3_Overrides(in *v1alpha4.Overrides, out *Overrides, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	return nil
}

// Convert_v1alpha4_Overrides_To_v1alpha3_Overrides is an autogenerated conversion function.
func Convert_v1alpha4_Overrides_To_v1alpha3_Overrides(in *v1alpha4.Overrides, out *Overrides, s conversion.Scope) error {
	return autoConvert_v1alpha4_Overrides_To_v1alpha3_Overrides(in, out, s)
}

func autoConvert_v1alpha3_RefreshPreferences_To_v1alpha4_RefreshPreferences(in *RefreshPreferences, out *v1alpha4.RefreshPreferences, s conversion.Scope) error {
	out.Strategy = (*string)(unsafe.Pointer(in.Strategy))
	out.InstanceWarmup = (*int64)(unsafe.Pointer(in.InstanceWarmup))
	out.MinHealthyPercentage = (*int64)(unsafe.Pointer(in.MinHealthyPercentage))
	return nil
}

// Convert_v1alpha3_RefreshPreferences_To_v1alpha4_RefreshPreferences is an autogenerated conversion function.
func Convert_v1alpha3_RefreshPreferences_To_v1alpha4_RefreshPreferences(in *RefreshPreferences, out *v1alpha4.RefreshPreferences, s conversion.Scope) error {
	return autoConvert_v1alpha3_RefreshPreferences_To_v1alpha4_RefreshPreferences(in, out, s)
}

func autoConvert_v1alpha4_RefreshPreferences_To_v1alpha3_RefreshPreferences(in *v1alpha4.RefreshPreferences, out *RefreshPreferences, s conversion.Scope) error {
	out.Strategy = (*string)(unsafe.Pointer(in.Strategy))
	out.InstanceWarmup = (*int64)(unsafe.Pointer(in.InstanceWarmup))
	out.MinHealthyPercentage = (*int64)(unsafe.Pointer(in.MinHealthyPercentage))
	return nil
}

// Convert_v1alpha4_RefreshPreferences_To_v1alpha3_RefreshPreferences is an autogenerated conversion function.
func Convert_v1alpha4_RefreshPreferences_To_v1alpha3_RefreshPreferences(in *v1alpha4.RefreshPreferences, out *RefreshPreferences, s conversion.Scope) error {
	return autoConvert_v1alpha4_RefreshPreferences_To_v1alpha3_RefreshPreferences(in, out, s)
}
