---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - image: gcr.io/cluster-api-provider-aws/cluster-api-aws-controller:0.0.3
          name: manager
---
