apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- machinedeployment.yaml
configurations:
- kustomizeconfig.yaml
patchesStrategicMerge:
- kustomizeversions.yaml
