load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["group.go"],
    importpath = "sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider",
    visibility = ["//visibility:public"],
)
