apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  namespace: system
  name: test1
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  providerConfig:
    value:
      apiVersion: "awsprovider.k8s.io/v1alpha1"
      kind: "AWSClusterProviderConfig"
      region: "us-west-2"
      sshKeyName: "default"
