apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSMachineTemplate
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: awsmachinetemplate-sample
spec:
  # Add fields here
  foo: bar
