---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  name: master-machine
  namespace: default
  labels:
    machine.openshift.io/cluster-api-cluster: aws-actuator-k8s
spec:
  metadata:
    labels:
      node-role.kubernetes.io/master: ""
  providerSpec:
    value:
      apiVersion: awsproviderconfig.openshift.io/v1beta1
      kind: AWSMachineProviderConfig
      ami:
        filters:
        - name: "tag:image_stage"
          values:
          - "base"
        - name: "tag:operating_system"
          values:
          - "rhel"
        - name: "tag:ready"
          values:
          - "yes"
      instanceType: m4.xlarge
      placement:
        region: us-east-1
        availabilityZone: us-east-1a
      subnet:
        filters:
          - name: "tag:Name"
            values:
            - "aws-actuator-k8s-worker-*"
      iamInstanceProfile:
        id: openshift_master_launch_instances
      keyName: libra
      securityGroups:
        - filters:
            - name: "tag:Name"
              values:
              - "aws-actuator-k8s-*"
      publicIp: true
      userDataSecret:
        name: master-user-data-secret
      credentialsSecret:
        name: aws-credentials-secret
