---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  name: aws-actuator-testing-machine
  namespace: test
  labels:
    machine.openshift.io/cluster-api-cluster: aws-actuator-k8s
spec:
  metadata:
    labels:
      node-role.kubernetes.io/compute: ""
      node-role.kubernetes.io/worker: ""
  providerSpec:
    value:
      apiVersion: awsproviderconfig.openshift.io/v1beta1
      kind: AWSMachineProviderConfig
      ami:
        filters:
        - name: "image_stage"
          values:
          - "base"
        - name: operating_system
          values:
          - "rhel"
        - name: ready
          values:
          - "yes"
      instanceType: m4.large
      placement:
        region: us-east-1a
        availabilityZone: us-east-1ac
      subnet:
        filters:
        - name: "tag:Name"
          values:
          - "aws-actuator-k8s-worker-*"
      publicIp: true
      iamInstanceProfile:
        id: meh-master-profile
      keyName: tectonic
      tags:
      - name: "kubernetes.io/cluster/meh"
        value: owned
      securityGroups:
      - filters:
        - name: "tag:Name"
          values:
          - "aws-actuator-k8s-*"
      userDataSecret:
        name: aws-actuator-user-data-secret
