apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: ${CLUSTER_CLASS_NAME}
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: AWSManagedControlPlaneTemplate
      name: "${CLUSTER_NAME}-control-plane"
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSManagedClusterTemplate
      name: "${CLUSTER_NAME}"
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              name: "${CLUSTER_NAME}-md-0"
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
              kind: EKSConfigTemplate
          infrastructure:
            ref:
              name: "${CLUSTER_NAME}-md-0"
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
              kind: AWSMachineTemplate
---
kind: AWSManagedClusterTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
metadata:
  name: "${CLUSTER_NAME}"
spec:
  template:
    spec: {}
---
kind: AWSManagedControlPlaneTemplate
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  template:
    spec:
      region: "${AWS_REGION}"
      sshKeyName: "${AWS_SSH_KEY_NAME}"
      version: "${KUBERNETES_VERSION}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      instanceType: "${AWS_NODE_MACHINE_TYPE}"
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
      sshKeyName: "${AWS_SSH_KEY_NAME}"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: EKSConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template: {}
