/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package crd

import (
	"os"
	"strings"
	"testing"
)

// TestAllCRDBasesInKustomization verifies that every CRD file in config/crd/bases/
// is referenced in config/crd/kustomization.yaml.
//
// Without this, a new CRD generated by controller-gen can be missing from
// clusterctl deployments while the controller still registers a watch for it,
// causing startup failures that unit tests (envtest) won't catch because
// envtest loads CRDs directly from the bases/ directory.
func TestAllCRDBasesInKustomization(t *testing.T) {
	kustomization, err := os.ReadFile("kustomization.yaml")
	if err != nil {
		t.Fatalf("failed to read kustomization.yaml: %v", err)
	}

	entries, err := os.ReadDir("bases")
	if err != nil {
		t.Fatalf("failed to read bases/ directory: %v", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".yaml") {
			continue
		}
		if !strings.Contains(string(kustomization), "bases/"+entry.Name()) {
			t.Errorf("bases/%s is not listed in kustomization.yaml — it will be missing from clusterctl deployments", entry.Name())
		}
	}
}
