apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aws-provider-controller-manager
  namespace: aws-provider-system
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
        - mountPath: /root/.aws
          name: credentials
      volumes:
      - name: credentials
        secret:
          secretName: credentials.cluster-api-provider-aws.sigs.k8s.io
