on:
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # tag=v5
        with:
          persist-credentials: false
      - uses: artyom/mdlinks@v0
        with:
          dir: 'docs/book'
