on:
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: artyom/mdlinks@371ca82eb52a1b3119b618dc9abc884c937c32d0 # v0.4.3
        with:
          dir: 'docs/book'
