/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package changelog

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"sigs.k8s.io/cluster-api-provider-aws/hack/tools/release-tools/internal/changelog"
)

// notesPRCmd returns the `notes-pr` cobra command.
func notesPRCmd() *cobra.Command {
	var (
		input        string
		version      string
		metadataPath string
		contract     string
	)

	cmd := &cobra.Command{
		Use:   "notes-pr",
		Short: "Prepend a contract front-matter block to a generated changelog, and update metadata.yaml for major/minor releases",
		Long: `Reads a changelog file already generated by the upstream release-notes tool
and rewrites it in place with a "contract" front-matter block prepended,
ready to commit as CHANGELOG/vX.Y.Z.md and open a PR with.

If --contract is not given, it defaults to the contract of the most
recent entry in metadata.yaml, since the contract rarely changes between
releases.

If --version has patch 0 (a main-targeted major/minor release), this also
appends the new {major, minor, contract} entry to metadata.yaml directly,
so it's committed as part of the same PR as the changelog (a required CI
check verifies this before merge). Patch releases (--version with a
non-zero patch) leave metadata.yaml untouched.`,
		RunE: func(_ *cobra.Command, _ []string) error {
			body, err := os.ReadFile(input) //nolint:gosec // input is an operator-supplied CLI flag
			if err != nil {
				return fmt.Errorf("reading %s: %w", input, err)
			}

			major, minor, patch, err := changelog.ParseVersion(version)
			if err != nil {
				return err
			}

			resolvedContract := contract
			if resolvedContract == "" {
				resolvedContract, err = changelog.DefaultContract(metadataPath)
				if err != nil {
					return fmt.Errorf("determining default contract: %w", err)
				}
			}

			if err := os.WriteFile(input, changelog.WithFrontMatter(resolvedContract, body), 0o600); err != nil {
				return fmt.Errorf("writing %s: %w", input, err)
			}

			if patch == 0 {
				if err := changelog.AppendReleaseSeries(metadataPath, major, minor, resolvedContract); err != nil {
					return fmt.Errorf("updating %s: %w", metadataPath, err)
				}
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&input, "input", "", "path to the generated changelog file to rewrite in place (required)")
	cmd.Flags().StringVar(&version, "version", "", "the version being released, e.g. v2.10.0 (required)")
	cmd.Flags().StringVar(&metadataPath, "metadata", "metadata.yaml", "path to metadata.yaml, used to default --contract and, for major/minor versions, updated in place")
	cmd.Flags().StringVar(&contract, "contract", "", "contract version to record (defaults to the latest entry in metadata.yaml)")
	_ = cmd.MarkFlagRequired("input")
	_ = cmd.MarkFlagRequired("version")

	return cmd
}
